owner: fpsecosystem
git-repo: helm-charts
charts-repo: https://fpsecosystem.github.io/helm-charts
target-branch: gh-pages
index-path: index.yaml
packages-with-index: false
release-name-template: "{{ .Name }}-{{ .Version }}"
package-path: .cr-release-packages
