{{- define "mariadb-library.database" -}}
{{- if .Values.database.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "mariadb-library.databaseName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb-library.labels" . | nindent 4 }}
    {{- with .Values.database.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mariadb-library.annotations" . | nindent 4 }}
    {{- with .Values.database.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mariaDbRef:
    name: {{ .Values.database.mariaDbRef.name }}
    {{- if .Values.database.mariaDbRef.namespace }}
    namespace: {{ .Values.database.mariaDbRef.namespace }}
    {{- end }}
  name: {{ include "mariadb-library.databaseName" . }}
  characterSet: {{ .Values.database.characterSet }}
  collate: {{ .Values.database.collate }}
{{- end }}
{{- end }}
