{{- define "mariadb-library.grant" -}}
{{- if .Values.grant.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ include "mariadb-library.fullname" . }}-grant
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb-library.labels" . | nindent 4 }}
    {{- with .Values.grant.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mariadb-library.annotations" . | nindent 4 }}
    {{- with .Values.grant.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mariaDbRef:
    name: {{ .Values.grant.mariaDbRef.name }}
    {{- if .Values.grant.mariaDbRef.namespace }}
    namespace: {{ .Values.grant.mariaDbRef.namespace }}
    {{- end }}
  privileges:
    {{- toYaml .Values.grant.privileges | nindent 4 }}
  database: {{ if .Values.grant.database }}{{ .Values.grant.database }}{{ else }}{{ include "mariadb-library.databaseName" . }}{{ end }}
  table: {{ .Values.grant.table }}
  username: {{ if .Values.grant.username }}{{ .Values.grant.username }}{{ else }}{{ include "mariadb-library.username" . }}{{ end }}
  host: {{ .Values.grant.host | quote }}
{{- end }}
{{- end }}
