{{- define "mariadb-library.secret" -}}
{{- if and .Values.user.enabled .Values.user.passwordSecret.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-library.passwordSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb-library.labels" . | nindent 4 }}
    {{- with .Values.user.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mariadb-library.annotations" . | nindent 4 }}
    {{- with .Values.user.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ .Values.user.passwordSecret.key }}: {{ include "mariadb-library.generatePassword" . | b64enc }}
{{- end }}
{{- end }}
