{{- define "mariadb-library.user" -}}
{{- if .Values.user.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "mariadb-library.username" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb-library.labels" . | nindent 4 }}
    {{- with .Values.user.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mariadb-library.annotations" . | nindent 4 }}
    {{- with .Values.user.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mariaDbRef:
    name: {{ .Values.user.mariaDbRef.name }}
    {{- if .Values.user.mariaDbRef.namespace }}
    namespace: {{ .Values.user.mariaDbRef.namespace }}
    {{- end }}
  passwordSecretKeyRef:
    name: {{ include "mariadb-library.passwordSecretName" . }}
    key: {{ .Values.user.passwordSecret.key }}
  name: {{ include "mariadb-library.username" . }}
  host: {{ .Values.user.host | quote }}
  maxUserConnections: {{ .Values.user.maxUserConnections }}
{{- end }}
{{- end }}
