{{- if .Values.imagePullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagepullsecret-library.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-library.labels" . | nindent 4 }}
    {{- with .Values.imagePullSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "imagepullsecret-library.annotations" . | nindent 4 }}
    {{- with .Values.imagePullSecret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagepullsecret-library.dockerConfigJson" . }}
{{- end }}
