# Example values for testing the mariadb-library-chart

# Database configuration
database:
  enabled: true
  name: "example-app-db"
  mariaDbRef:
    name: "mariadb-instance"
    namespace: "mariadb-system"
  characterSet: "utf8mb4"
  collate: "utf8mb4_unicode_ci"

# User configuration
user:
  enabled: true
  name: "example-app-user"
  passwordSecret:
    generate: true
    passwordLength: 24
  host: "%"
  mariaDbRef:
    name: "mariadb-instance"
    namespace: "mariadb-system"
  maxUserConnections: 20

# Grant configuration
grant:
  enabled: true
  privileges:
  - "SELECT"
  - "INSERT"
  - "UPDATE"
  - "DELETE"
  - "CREATE"
  - "DROP"
  table: "*"
  host: "%"
  mariaDbRef:
    name: "mariadb-instance"
    namespace: "mariadb-system"

# Common labels and annotations
commonLabels:
  app.kubernetes.io/part-of: "example-application"

commonAnnotations:
  example.com/managed-by: "helm"
