{{/*
Secret containing database configuration for Symfony
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- with (include "application.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "application.databaseUrl" . | quote }}
