{{/*
Secret containing database configuration for the application
*/}}
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" $ }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- with (include "application.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DATABASE_URL_TEMPLATE: {{ include "application.databaseUrl" . | quote }}
  DATABASE_HOST: {{ include "application.mariadbHost" . | quote }}
  DATABASE_PORT: {{ include "application.mariadbPort" . | quote }}
  DATABASE_NAME: {{ include "application.databaseName" . | quote }}
  DATABASE_USERNAME: {{ include "application.username" . | quote }}
  DATABASE_CHARSET: {{ .Values.mariadb.connection.options.charset | quote }}
  DATABASE_SERVER_VERSION: {{ include "application.mariadbVersion" . | quote }}
{{- end }}
