{{/*
Test template to verify ingress rendering
Only enabled when explicitly requested via values
*/}}
{{- if and .Values.ingress.main.enabled .Values.ingress.test.enabled }}
# CUSTOM INGRESS TEST: Enabled = {{ .Values.ingress.test.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" $ }}-test
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ include "application.dynamicIngressHost" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "application.fullname" $ }}
                port:
                  name: http
{{- end }}
