{{- /*
MariaDB Resources for application
This template creates MariaDB database, user, grant, and password secret resources
*/ -}}

{{/* Password Secret */}}
{{- if and .Values.mariadb.enabled .Values.mariadb.user.enabled .Values.mariadb.user.passwordSecret.generate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.mariadb.user.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
    {{- with .Values.mariadb.user.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ .Values.mariadb.user.passwordSecret.key }}: {{ include "application.generatePassword" . | b64enc }}
{{- end }}

{{/* Database Resource */}}
{{- if and .Values.mariadb.enabled .Values.mariadb.database.enabled }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "application.databaseName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.mariadb.database.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
    {{- with .Values.mariadb.database.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mariaDbRef:
    name: {{ .Values.mariadb.database.mariaDbRef.name }}
    {{- if .Values.mariadb.database.mariaDbRef.namespace }}
    namespace: {{ .Values.mariadb.database.mariaDbRef.namespace }}
    {{- end }}
  name: {{ include "application.databaseName" . }}
  characterSet: {{ .Values.mariadb.database.characterSet }}
  collate: {{ .Values.mariadb.database.collate }}
{{- end }}

{{/* User Resource */}}
{{- if and .Values.mariadb.enabled .Values.mariadb.user.enabled }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "application.username" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.mariadb.user.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
    {{- with .Values.mariadb.user.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mariaDbRef:
    name: {{ .Values.mariadb.user.mariaDbRef.name }}
    {{- if .Values.mariadb.user.mariaDbRef.namespace }}
    namespace: {{ .Values.mariadb.user.mariaDbRef.namespace }}
    {{- end }}
  passwordSecretKeyRef:
    name: {{ include "application.passwordSecretName" . }}
    key: {{ .Values.mariadb.user.passwordSecret.key }}
  name: {{ include "application.username" . }}
  host: {{ .Values.mariadb.user.host | quote }}
  maxUserConnections: {{ .Values.mariadb.user.maxUserConnections }}
{{- end }}

{{/* Grant Resource */}}
{{- if and .Values.mariadb.enabled .Values.mariadb.grant.enabled }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ include "application.fullname" . }}-grant
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.mariadb.grant.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
    {{- with .Values.mariadb.grant.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  mariaDbRef:
    name: {{ .Values.mariadb.grant.mariaDbRef.name }}
    {{- if .Values.mariadb.grant.mariaDbRef.namespace }}
    namespace: {{ .Values.mariadb.grant.mariaDbRef.namespace }}
    {{- end }}
  privileges:
    {{- toYaml .Values.mariadb.grant.privileges | nindent 4 }}
  database: {{ if .Values.mariadb.grant.database }}{{ .Values.mariadb.grant.database }}{{ else }}{{ include "application.databaseName" . }}{{ end }}
  table: {{ .Values.mariadb.grant.table | quote }}
  username: {{ if .Values.mariadb.grant.username }}{{ .Values.mariadb.grant.username }}{{ else }}{{ include "application.username" . }}{{ end }}
  host: {{ .Values.mariadb.grant.host | quote }}
{{- end }}
