# Example values for Symfony application with MariaDB integration
# This demonstrates different configuration scenarios

# Symfony application configuration
app:
  name: "symfony-demo"
  image:
    repository: "symfony/demo"
    tag: "latest"
    pullPolicy: "IfNotPresent"

  # Application environment (dev/test/prod)
  env: "prod"

  # Symfony-specific environment variables
  symfonyEnv:
    APP_SECRET: "ThisTokenIsNotSoSecretChangeIt"
    MAILER_DSN: "null://null"
    CORS_ALLOW_ORIGIN: "^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$"

  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  # Ingress configuration (disabled by default)
  ingress:
    enabled: false
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
    - host: symfony-demo.local
      paths:
      - path: /
        pathType: Prefix
    tls: []
    # tls:
    #   - secretName: symfony-demo-tls
    #     hosts:
    #       - symfony-demo.local

    # Resources for production use
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi

  # Pod configuration
  replicaCount: 2

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

# MariaDB configuration using the library chart
mariadb-library-chart:
  database:
    enabled: true
    name: "symfony_production"
    mariaDbRef:
      name: "mariadb-primary"
      namespace: "" # Uses same namespace as release
    characterSet: "utf8mb4"
    collate: "utf8mb4_unicode_ci"
    labels:
      app.kubernetes.io/component: "database"
    annotations:
      "helm.sh/resource-policy": "keep"

  user:
    enabled: true
    name: "symfony_app_user"
    passwordSecret:
      name: "" # Will be auto-generated as {release-name}-password
      key: "password"
      generate: true
      passwordLength: 32
    host: "%"
    maxUserConnections: 50
    mariaDbRef:
      name: "mariadb-primary"
      namespace: ""
    labels:
      app.kubernetes.io/component: "database-user"
    annotations:
      "helm.sh/resource-policy": "keep"

  grant:
    enabled: true
    database: "symfony_production"
    username: "symfony_app_user"
    table: "*"
    privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
    - "CREATE"
    - "DROP"
    - "INDEX"
    - "ALTER"
    - "REFERENCES"
    - "CREATE TEMPORARY TABLES"
    - "LOCK TABLES"
    - "EXECUTE"
    - "CREATE VIEW"
    - "SHOW VIEW"
    - "CREATE ROUTINE"
    - "ALTER ROUTINE"
    host: "%"
    mariaDbRef:
      name: "mariadb-primary"
      namespace: ""
    labels:
      app.kubernetes.io/component: "database-grant"
    annotations:
      "helm.sh/resource-policy": "keep"

# Database connection configuration for Symfony
database:
  # MariaDB server configuration
  server:
    host: "mariadb-primary.default.svc.cluster.local"
    port: 3306

  # Connection options for Symfony DATABASE_URL
  options:
    charset: "utf8mb4"
    serverVersion: "10.11.0-MariaDB"
    # Additional Doctrine DBAL options can be added here
    driverOptions: {}

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/component: "web-application"
  app.kubernetes.io/part-of: "symfony-stack"
  environment: "production"

# Common annotations applied to all resources
commonAnnotations:
  "helm.sh/resource-policy": "keep"
  "meta.helm.sh/release-name": "symfony-demo"
