# Example values for custom PHP application
# This file demonstrates how to configure the chart for a custom PHP application

# Image configuration for custom PHP app
image:
  repository: "your-registry/custom-php-app"
  tag: "production"
  pullPolicy: "Always"

# Application configuration
appConfig:
  APP_ENV: "production"
  MAILER_DSN: "sendgrid+smtp://apikey:your-sendgrid-key@smtp.sendgrid.net:587"
  APP_SECRET: "custom-php-app-secret-key"

  custom:
    PHP_MEMORY_LIMIT: "256M"
    PHP_MAX_EXECUTION_TIME: "60"
    PHP_UPLOAD_MAX_FILESIZE: "10M"
    REDIS_HOST: "redis.default.svc.cluster.local"
    REDIS_PORT: "6379"
    API_BASE_URL: "https://api.example.com"

# Resources for custom PHP application
resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Service configuration for custom PHP app
service:
  main:
    ports:
      http:
        port: 80
        targetPort: 8080
        protocol: HTTP
