# Symfony Application Example Values - With Fallback Configuration
# This file demonstrates explicit fallback values for advanced usage scenarios
# where you want to override the automatic operator detection

# bjw-s common library configuration
controllers:
  main:
    annotations: {}
    labels: {}
    containers:
      main:
        image:
          repository: "symfony/demo"
          tag: "latest"
          pullPolicy: "IfNotPresent"
        env:
          APP_ENV: "prod"
          APP_SECRET: "change-me-in-production"
          MAILER_DSN: "null://null"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
    replicas: 1

# Service configuration
service:
  main:
    ports:
      http:
        port: 80
        targetPort: 8000
        protocol: HTTP

# Ingress configuration
ingress:
  main:
    enabled: true
    className: ""
    annotations: {}
    dynamicDomain: ""
    hosts:
    - host: "placeholder.example.com"
      paths:
      - path: /
        pathType: Prefix
        service:
          name: main
          port: http
    tls: []

# Database connection configuration with explicit fallback values
database:
  # MariaDB reference for operator-based dynamic detection
  mariaDbRef:
    name: "mariadb-primary"
    namespace: ""

  # Explicit server configuration (overrides automatic detection)
  server:
    host: "mariadb-primary.default.svc.cluster.local"
    port: 3306

  # Connection options for Symfony DATABASE_URL
  options:
    charset: "utf8mb4"
    serverVersion: "10.11.0-MariaDB" # Explicit version override
    driverOptions: {}

# Common labels and annotations
commonLabels:
  app.kubernetes.io/component: "web-application"
  app.kubernetes.io/part-of: "symfony-stack"

commonAnnotations:
  "helm.sh/resource-policy": "keep"
