name: Lint and Test Charts

on:
  pull_request:
    paths:
    - 'charts/**'
  push:
    branches:
    - main
    paths:
    - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1

    - name: Run chart-testing (list)
      id: list
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Run chart-testing (lint)
      if: steps.list.outputs.changed == 'true'
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    - name: Create kind cluster
      if: steps.list.outputs.changed == 'true'
      uses: helm/kind-action@v1.10.0

    - name: Install MariaDB Operator (for testing)
      if: steps.list.outputs.changed == 'true'
      run: |
        # Install MariaDB Operator for testing
        helm repo add mariadb-operator https://mariadb-operator.github.io/mariadb-operator
        helm repo update
        helm install mariadb-operator mariadb-operator/mariadb-operator \
          --namespace mariadb-system \
          --create-namespace \
          --wait

    - name: Run chart-testing (install)
      if: steps.list.outputs.changed == 'true'
      run: ct install --target-branch ${{ github.event.repository.default_branch }}
