name: Release Charts

on:
  push:
    branches:
    - main
    paths:
    - 'helm-charts/**'
  pull_request:
    paths:
    - 'helm-charts/**'
  workflow_dispatch:


jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Check for chart changes and version bump
      run: |
        # Check if any chart version has been updated in charts/
        if git diff HEAD~1 --name-only | grep -E "charts/.+/Chart.yaml"; then
          echo "Chart.yaml was modified, proceeding with release"
        else
          echo "No changes to Chart.yaml files, skipping release"
          exit 0
        fi

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - name: Add chart-releaser
      run: |
        wget https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz
        tar -xzf chart-releaser_1.6.1_linux_amd64.tar.gz
        sudo mv cr /usr/local/bin/cr

    - name: Package and release charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        # Create .cr-release-packages directory
        mkdir -p .cr-release-packages

        # Package all charts in helm-charts/
        for chart in helm-charts/*; do
          if [ -d "$chart" ] && [ -f "$chart/Chart.yaml" ]; then
            echo "Packaging $chart..."
            # Copy dependencies to charts/ before packaging
            mkdir -p "$chart/charts"
            for dep in $(yq e '.dependencies[].name' "$chart/Chart.yaml"); do
              dep_version=$(yq e ".dependencies[] | select(.name == \"$dep\") | .version" "$chart/Chart.yaml")
              dep_file="helm-charts/$dep-$dep_version.tgz"
              if [ -f "$dep_file" ]; then
                cp "$dep_file" "$chart/charts/"
              else
                # Try workspace root as fallback
                if [ -f "$dep-$dep_version.tgz" ]; then
                  cp "$dep-$dep_version.tgz" "$chart/charts/"
                fi
              fi
            done
            helm package "$chart" --destination .cr-release-packages
          fi
        done

        # Upload chart packages to GitHub Releases (skip if already exists)
        cr upload --config .github/cr.yaml --skip-existing

        # Update Helm repository index and push to gh-pages
        cr index --config .github/cr.yaml --push
